os: linux
language: rust
deploy:
  provider: cargo
  token: "$CRATES_TOKEN"
  on:
    branch: master
    tags: true
env:
  global:
    secure: QH/L+tucheemWaZU6HxJfqdiTGKbZ4lR2tICjiWESqne2OBn9uIZNuD0EN7rvxHNcSksMyE588G7cFFlURqfnEUVUnH/i6/eCPkfGfaxXKQQbSTyUIXeeBZzGyBl+GgqkF1EOtPROegqFC+ObReOoQNhoC2LwH8sgStc5MWQ6PCxH4/Ju+32IOxMZq1NCN3Gn7iuIzJGcFgDFX4h0D5rTP/3H3L1hkKO7vv7J9GALpvnL6Q7EPwi5IqgBDFhw/sUDNOTIxtK3fSfrTUGrh1cyOj5wm3yUrQJTu9yebl/4moAHNMOb8kiFnmlnVvlnN4rb9lscnt83iS2TIj+UFQqLil+5mduj4FlO33LslSRs1GxvQLxnqyCt8dF7SNK7k88/nUwTfDAIFJOP7pYvooChlVcwFULpLRTn1fkDOLYBlQrlQI6BOkf87UtP2BZT1WRspMFObgxX8YXq5PBX3QMG11MRYklIGGxxyazDk/kiORLpYodMoEQ7AoCFgFu6LaDXM81Poqz5kIVj9vbZ8NDyIpYjF+TbybLOz5gcjiTjQte+trOUKmADN7DozNMFmA3PH2rBLEEwrtYxkhdJPHfpDLjK/euPnoVHKcPi0AdPQAFo2Sm7pa13GZ+qAKd5uzh0gxUrpQKqDBuRSwbzFrfzamgoDUngd10a+Iw99yZc4I=
